name: Build and test NodeJS wrapper
on:
  push:
    paths:
      - '.github/workflows/build-node.yaml'
      - 'package.json'
      - 'package-lock.json'
      - 'src/**'
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    paths:
      - '.github/workflows/build-node.yaml'
      - 'package.json'
      - 'package-lock.json'
      - 'src/**'
  workflow_dispatch:

jobs:
  build-node:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Build wrapper
        run: npm run build
